[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LOICA"
authors = [{name = "Gonzalo Vidal", email = "gsvidal@uc.cl"}]
dynamic = ["version", "description"]
